/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vigilante;

/**
 *
 * @author josue
 */
public class SalidaVisitante extends javax.swing.JFrame {

    /**
     * Creates new form SalidaVisitante
     */
    public SalidaVisitante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnSalida = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel67 = new javax.swing.JPanel();
        jlblTipoEntrada34 = new javax.swing.JLabel();
        jlblIdResidencia29 = new javax.swing.JLabel();
        jlblMotivoEntrada58 = new javax.swing.JLabel();
        jlblMotivoEntrada59 = new javax.swing.JLabel();
        jcmbTipoIS30 = new javax.swing.JComboBox<>();
        jcmbIdResidencia29 = new javax.swing.JComboBox<>();
        jFormattedTextField33 = new javax.swing.JFormattedTextField();
        jScrollPane59 = new javax.swing.JScrollPane();
        jTextArea30 = new javax.swing.JTextArea();
        jrdbTrueEntrada29 = new javax.swing.JRadioButton();
        jrdbFalseEntrada29 = new javax.swing.JRadioButton();
        jlblEntrada29 = new javax.swing.JLabel();
        jScrollPane60 = new javax.swing.JScrollPane();
        jTable30 = new javax.swing.JTable();
        jPanel66 = new javax.swing.JPanel();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jlblTipoEntrada2 = new javax.swing.JLabel();
        jlblTipoEntrada3 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jlblTipoEntrada4 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jlblTipoEntrada5 = new javax.swing.JLabel();
        jcmbTipoIS1 = new javax.swing.JComboBox<>();
        jlblTipoEntrada1 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        llblCerrar = new javax.swing.JLabel();
        btnTheme = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(57, 62, 70));
        jPanel2.setForeground(new java.awt.Color(57, 62, 70));
        jPanel2.setPreferredSize(new java.awt.Dimension(290, 768));

        jPanel6.setBackground(new java.awt.Color(57, 62, 70));

        jPanel7.setBackground(new java.awt.Color(57, 62, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema Vigilantes");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(57, 62, 70));

        btnSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vigilante/Imagenes/cerrar-sesion-white.png"))); // NOI18N
        btnSalida.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(btnSalida)
                .addGap(49, 49, 49))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(btnSalida)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 290, 770);

        jPanel3.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel3.setLayout(null);

        jPanel67.setBackground(new java.awt.Color(255, 255, 255));
        jPanel67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblTipoEntrada34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblTipoEntrada34.setText("Apellido:");

        jlblIdResidencia29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblIdResidencia29.setText("Residencia a visitar:");

        jlblMotivoEntrada58.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblMotivoEntrada58.setText("Motivo de visita:");

        jlblMotivoEntrada59.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblMotivoEntrada59.setText("Hora de la entrada:");

        jcmbTipoIS30.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jcmbIdResidencia29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jcmbIdResidencia29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbIdResidenciaActionPerformed(evt);
            }
        });

        jFormattedTextField33.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField33.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jFormattedTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jTextArea30.setColumns(20);
        jTextArea30.setRows(5);
        jScrollPane59.setViewportView(jTextArea30);

        jrdbTrueEntrada29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jrdbTrueEntrada29.setText("SI");

        jrdbFalseEntrada29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jrdbFalseEntrada29.setText("NO");

        jlblEntrada29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblEntrada29.setText("¿Se le permitio la entrada?");

        jTable30.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificación", "Nombre", "Apellido", "Motivo", "Hora de entrada", "Estado del Ingreso", "Tipo de entrada", "Zona", "Residencia"
            }
        ));
        jScrollPane60.setViewportView(jTable30);

        jPanel66.setBackground(new java.awt.Color(255, 255, 255));

        jButton118.setBackground(new java.awt.Color(255, 211, 105));
        jButton118.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton118.setText("Registrar");
        jButton118.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 105), 3, true));
        jButton118.setContentAreaFilled(false);
        jButton118.setFocusable(false);

        jButton119.setBackground(new java.awt.Color(255, 211, 105));
        jButton119.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton119.setText("Agregar");
        jButton119.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 105), 3, true));
        jButton119.setContentAreaFilled(false);
        jButton119.setFocusable(false);

        jButton120.setBackground(new java.awt.Color(255, 211, 105));
        jButton120.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton120.setText("Modificar");
        jButton120.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 105), 3, true));
        jButton120.setContentAreaFilled(false);
        jButton120.setFocusable(false);

        jButton121.setBackground(new java.awt.Color(255, 211, 105));
        jButton121.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton121.setText("Limpiar");
        jButton121.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 105), 3, true));
        jButton121.setContentAreaFilled(false);
        jButton121.setFocusable(false);

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel66Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jButton120, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jButton121, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jButton118, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel66Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jButton119, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(708, Short.MAX_VALUE)))
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel66Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton118, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton120, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton121, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel66Layout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(jButton119, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)))
        );

        jlblTipoEntrada2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblTipoEntrada2.setText("Lugar donde ingreso el visitante: ");

        jlblTipoEntrada3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblTipoEntrada3.setText("Nombre:");

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jlblTipoEntrada4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblTipoEntrada4.setText("DUI:");

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jlblTipoEntrada5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblTipoEntrada5.setText("Tipo de entrada:");

        jcmbTipoIS1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jcmbTipoIS1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcmbTipoIS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbTipoIS1ActionPerformed(evt);
            }
        });

        jlblTipoEntrada1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlblTipoEntrada1.setForeground(new java.awt.Color(255, 211, 105));
        jlblTipoEntrada1.setText("Ingreso de Visitantes");

        javax.swing.GroupLayout jPanel67Layout = new javax.swing.GroupLayout(jPanel67);
        jPanel67.setLayout(jPanel67Layout);
        jPanel67Layout.setHorizontalGroup(
            jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel67Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel67Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane60, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel67Layout.createSequentialGroup()
                        .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblMotivoEntrada58)
                            .addComponent(jScrollPane59, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblEntrada29)
                            .addGroup(jPanel67Layout.createSequentialGroup()
                                .addComponent(jrdbTrueEntrada29)
                                .addGap(36, 36, 36)
                                .addComponent(jrdbFalseEntrada29))
                            .addComponent(jcmbTipoIS30, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTipoEntrada5)))
                    .addGroup(jPanel67Layout.createSequentialGroup()
                        .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlblTipoEntrada2)
                                .addComponent(jFormattedTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcmbTipoIS1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblTipoEntrada3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblTipoEntrada34)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblIdResidencia29)
                            .addComponent(jcmbIdResidencia29, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblTipoEntrada4)
                            .addComponent(jFormattedTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jlblMotivoEntrada59)
                            .addComponent(jFormattedTextField2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel67Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(jlblTipoEntrada1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel67Layout.setVerticalGroup(
            jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel67Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTipoEntrada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel67Layout.createSequentialGroup()
                        .addComponent(jlblTipoEntrada4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlblMotivoEntrada59)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel67Layout.createSequentialGroup()
                        .addComponent(jlblTipoEntrada34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlblIdResidencia29)
                        .addGap(18, 18, 18)
                        .addComponent(jcmbIdResidencia29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel67Layout.createSequentialGroup()
                        .addComponent(jlblTipoEntrada3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlblTipoEntrada2)
                        .addGap(18, 18, 18)
                        .addComponent(jcmbTipoIS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTipoEntrada5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblMotivoEntrada58))
                .addGap(18, 18, 18)
                .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel67Layout.createSequentialGroup()
                        .addComponent(jcmbTipoIS30, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jlblEntrada29)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrdbTrueEntrada29)
                            .addComponent(jrdbFalseEntrada29)))
                    .addComponent(jScrollPane59, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane60, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel67);
        jPanel67.setBounds(10, 10, 1050, 680);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(290, 60, 1098, 710);

        jPanel21.setBackground(new java.awt.Color(255, 211, 105));
        jPanel21.setMinimumSize(new java.awt.Dimension(1082, 61));

        llblCerrar.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        llblCerrar.setText("x");
        llblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llblCerrarMouseClicked(evt);
            }
        });

        btnTheme.setAlignmentY(0.7F);
        btnTheme.setContentAreaFilled(false);
        btnTheme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Administrador");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Cargo:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Josué Alemán");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Usuario:");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(219, 219, 219)
                .addComponent(btnTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(llblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(llblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)))))
                .addContainerGap())
        );

        getContentPane().add(jPanel21);
        jPanel21.setBounds(290, 0, 1080, 61);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbTipoIS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbTipoIS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbTipoIS1ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jcmbIdResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbIdResidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbIdResidenciaActionPerformed

    private void llblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llblCerrarMouseClicked
        Menu menu = new Menu();
        menu.show();
        dispose();
    }//GEN-LAST:event_llblCerrarMouseClicked

    private void btnThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalidaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalidaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalidaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalidaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalidaVisitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnTheme;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField20;
    private javax.swing.JFormattedTextField jFormattedTextField21;
    private javax.swing.JFormattedTextField jFormattedTextField22;
    private javax.swing.JFormattedTextField jFormattedTextField23;
    private javax.swing.JFormattedTextField jFormattedTextField24;
    private javax.swing.JFormattedTextField jFormattedTextField25;
    private javax.swing.JFormattedTextField jFormattedTextField26;
    private javax.swing.JFormattedTextField jFormattedTextField27;
    private javax.swing.JFormattedTextField jFormattedTextField28;
    private javax.swing.JFormattedTextField jFormattedTextField29;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField30;
    private javax.swing.JFormattedTextField jFormattedTextField31;
    private javax.swing.JFormattedTextField jFormattedTextField32;
    private javax.swing.JFormattedTextField jFormattedTextField33;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JScrollPane jScrollPane48;
    private javax.swing.JScrollPane jScrollPane49;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JScrollPane jScrollPane51;
    private javax.swing.JScrollPane jScrollPane52;
    private javax.swing.JScrollPane jScrollPane53;
    private javax.swing.JScrollPane jScrollPane54;
    private javax.swing.JScrollPane jScrollPane55;
    private javax.swing.JScrollPane jScrollPane56;
    private javax.swing.JScrollPane jScrollPane57;
    private javax.swing.JScrollPane jScrollPane58;
    private javax.swing.JScrollPane jScrollPane59;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane60;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable14;
    private javax.swing.JTable jTable15;
    private javax.swing.JTable jTable16;
    private javax.swing.JTable jTable17;
    private javax.swing.JTable jTable18;
    private javax.swing.JTable jTable19;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable20;
    private javax.swing.JTable jTable21;
    private javax.swing.JTable jTable22;
    private javax.swing.JTable jTable23;
    private javax.swing.JTable jTable24;
    private javax.swing.JTable jTable25;
    private javax.swing.JTable jTable26;
    private javax.swing.JTable jTable27;
    private javax.swing.JTable jTable28;
    private javax.swing.JTable jTable29;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable30;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea25;
    private javax.swing.JTextArea jTextArea26;
    private javax.swing.JTextArea jTextArea27;
    private javax.swing.JTextArea jTextArea28;
    private javax.swing.JTextArea jTextArea29;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea30;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JComboBox<String> jcmbIdResidencia;
    private javax.swing.JComboBox<String> jcmbIdResidencia1;
    private javax.swing.JComboBox<String> jcmbIdResidencia10;
    private javax.swing.JComboBox<String> jcmbIdResidencia11;
    private javax.swing.JComboBox<String> jcmbIdResidencia12;
    private javax.swing.JComboBox<String> jcmbIdResidencia13;
    private javax.swing.JComboBox<String> jcmbIdResidencia14;
    private javax.swing.JComboBox<String> jcmbIdResidencia15;
    private javax.swing.JComboBox<String> jcmbIdResidencia16;
    private javax.swing.JComboBox<String> jcmbIdResidencia17;
    private javax.swing.JComboBox<String> jcmbIdResidencia18;
    private javax.swing.JComboBox<String> jcmbIdResidencia19;
    private javax.swing.JComboBox<String> jcmbIdResidencia2;
    private javax.swing.JComboBox<String> jcmbIdResidencia20;
    private javax.swing.JComboBox<String> jcmbIdResidencia21;
    private javax.swing.JComboBox<String> jcmbIdResidencia22;
    private javax.swing.JComboBox<String> jcmbIdResidencia23;
    private javax.swing.JComboBox<String> jcmbIdResidencia24;
    private javax.swing.JComboBox<String> jcmbIdResidencia25;
    private javax.swing.JComboBox<String> jcmbIdResidencia26;
    private javax.swing.JComboBox<String> jcmbIdResidencia27;
    private javax.swing.JComboBox<String> jcmbIdResidencia28;
    private javax.swing.JComboBox<String> jcmbIdResidencia29;
    private javax.swing.JComboBox<String> jcmbIdResidencia3;
    private javax.swing.JComboBox<String> jcmbIdResidencia4;
    private javax.swing.JComboBox<String> jcmbIdResidencia5;
    private javax.swing.JComboBox<String> jcmbIdResidencia6;
    private javax.swing.JComboBox<String> jcmbIdResidencia7;
    private javax.swing.JComboBox<String> jcmbIdResidencia8;
    private javax.swing.JComboBox<String> jcmbIdResidencia9;
    private javax.swing.JComboBox<String> jcmbTipoIS;
    private javax.swing.JComboBox<String> jcmbTipoIS1;
    private javax.swing.JComboBox<String> jcmbTipoIS10;
    private javax.swing.JComboBox<String> jcmbTipoIS11;
    private javax.swing.JComboBox<String> jcmbTipoIS12;
    private javax.swing.JComboBox<String> jcmbTipoIS13;
    private javax.swing.JComboBox<String> jcmbTipoIS14;
    private javax.swing.JComboBox<String> jcmbTipoIS15;
    private javax.swing.JComboBox<String> jcmbTipoIS16;
    private javax.swing.JComboBox<String> jcmbTipoIS17;
    private javax.swing.JComboBox<String> jcmbTipoIS18;
    private javax.swing.JComboBox<String> jcmbTipoIS19;
    private javax.swing.JComboBox<String> jcmbTipoIS2;
    private javax.swing.JComboBox<String> jcmbTipoIS20;
    private javax.swing.JComboBox<String> jcmbTipoIS21;
    private javax.swing.JComboBox<String> jcmbTipoIS22;
    private javax.swing.JComboBox<String> jcmbTipoIS23;
    private javax.swing.JComboBox<String> jcmbTipoIS24;
    private javax.swing.JComboBox<String> jcmbTipoIS25;
    private javax.swing.JComboBox<String> jcmbTipoIS26;
    private javax.swing.JComboBox<String> jcmbTipoIS27;
    private javax.swing.JComboBox<String> jcmbTipoIS28;
    private javax.swing.JComboBox<String> jcmbTipoIS29;
    private javax.swing.JComboBox<String> jcmbTipoIS3;
    private javax.swing.JComboBox<String> jcmbTipoIS30;
    private javax.swing.JComboBox<String> jcmbTipoIS4;
    private javax.swing.JComboBox<String> jcmbTipoIS5;
    private javax.swing.JComboBox<String> jcmbTipoIS6;
    private javax.swing.JComboBox<String> jcmbTipoIS7;
    private javax.swing.JComboBox<String> jcmbTipoIS8;
    private javax.swing.JComboBox<String> jcmbTipoIS9;
    private javax.swing.JLabel jlblEntrada;
    private javax.swing.JLabel jlblEntrada1;
    private javax.swing.JLabel jlblEntrada10;
    private javax.swing.JLabel jlblEntrada11;
    private javax.swing.JLabel jlblEntrada12;
    private javax.swing.JLabel jlblEntrada13;
    private javax.swing.JLabel jlblEntrada14;
    private javax.swing.JLabel jlblEntrada15;
    private javax.swing.JLabel jlblEntrada16;
    private javax.swing.JLabel jlblEntrada17;
    private javax.swing.JLabel jlblEntrada18;
    private javax.swing.JLabel jlblEntrada19;
    private javax.swing.JLabel jlblEntrada2;
    private javax.swing.JLabel jlblEntrada20;
    private javax.swing.JLabel jlblEntrada21;
    private javax.swing.JLabel jlblEntrada22;
    private javax.swing.JLabel jlblEntrada23;
    private javax.swing.JLabel jlblEntrada24;
    private javax.swing.JLabel jlblEntrada25;
    private javax.swing.JLabel jlblEntrada26;
    private javax.swing.JLabel jlblEntrada27;
    private javax.swing.JLabel jlblEntrada28;
    private javax.swing.JLabel jlblEntrada29;
    private javax.swing.JLabel jlblEntrada3;
    private javax.swing.JLabel jlblEntrada4;
    private javax.swing.JLabel jlblEntrada5;
    private javax.swing.JLabel jlblEntrada6;
    private javax.swing.JLabel jlblEntrada7;
    private javax.swing.JLabel jlblEntrada8;
    private javax.swing.JLabel jlblEntrada9;
    private javax.swing.JLabel jlblIdResidencia;
    private javax.swing.JLabel jlblIdResidencia1;
    private javax.swing.JLabel jlblIdResidencia10;
    private javax.swing.JLabel jlblIdResidencia11;
    private javax.swing.JLabel jlblIdResidencia12;
    private javax.swing.JLabel jlblIdResidencia13;
    private javax.swing.JLabel jlblIdResidencia14;
    private javax.swing.JLabel jlblIdResidencia15;
    private javax.swing.JLabel jlblIdResidencia16;
    private javax.swing.JLabel jlblIdResidencia17;
    private javax.swing.JLabel jlblIdResidencia18;
    private javax.swing.JLabel jlblIdResidencia19;
    private javax.swing.JLabel jlblIdResidencia2;
    private javax.swing.JLabel jlblIdResidencia20;
    private javax.swing.JLabel jlblIdResidencia21;
    private javax.swing.JLabel jlblIdResidencia22;
    private javax.swing.JLabel jlblIdResidencia23;
    private javax.swing.JLabel jlblIdResidencia24;
    private javax.swing.JLabel jlblIdResidencia25;
    private javax.swing.JLabel jlblIdResidencia26;
    private javax.swing.JLabel jlblIdResidencia27;
    private javax.swing.JLabel jlblIdResidencia28;
    private javax.swing.JLabel jlblIdResidencia29;
    private javax.swing.JLabel jlblIdResidencia3;
    private javax.swing.JLabel jlblIdResidencia4;
    private javax.swing.JLabel jlblIdResidencia5;
    private javax.swing.JLabel jlblIdResidencia6;
    private javax.swing.JLabel jlblIdResidencia7;
    private javax.swing.JLabel jlblIdResidencia8;
    private javax.swing.JLabel jlblIdResidencia9;
    private javax.swing.JLabel jlblMotivoEntrada;
    private javax.swing.JLabel jlblMotivoEntrada1;
    private javax.swing.JLabel jlblMotivoEntrada10;
    private javax.swing.JLabel jlblMotivoEntrada11;
    private javax.swing.JLabel jlblMotivoEntrada12;
    private javax.swing.JLabel jlblMotivoEntrada13;
    private javax.swing.JLabel jlblMotivoEntrada14;
    private javax.swing.JLabel jlblMotivoEntrada15;
    private javax.swing.JLabel jlblMotivoEntrada16;
    private javax.swing.JLabel jlblMotivoEntrada17;
    private javax.swing.JLabel jlblMotivoEntrada18;
    private javax.swing.JLabel jlblMotivoEntrada19;
    private javax.swing.JLabel jlblMotivoEntrada2;
    private javax.swing.JLabel jlblMotivoEntrada20;
    private javax.swing.JLabel jlblMotivoEntrada21;
    private javax.swing.JLabel jlblMotivoEntrada22;
    private javax.swing.JLabel jlblMotivoEntrada23;
    private javax.swing.JLabel jlblMotivoEntrada24;
    private javax.swing.JLabel jlblMotivoEntrada25;
    private javax.swing.JLabel jlblMotivoEntrada26;
    private javax.swing.JLabel jlblMotivoEntrada27;
    private javax.swing.JLabel jlblMotivoEntrada28;
    private javax.swing.JLabel jlblMotivoEntrada29;
    private javax.swing.JLabel jlblMotivoEntrada3;
    private javax.swing.JLabel jlblMotivoEntrada30;
    private javax.swing.JLabel jlblMotivoEntrada31;
    private javax.swing.JLabel jlblMotivoEntrada32;
    private javax.swing.JLabel jlblMotivoEntrada33;
    private javax.swing.JLabel jlblMotivoEntrada34;
    private javax.swing.JLabel jlblMotivoEntrada35;
    private javax.swing.JLabel jlblMotivoEntrada36;
    private javax.swing.JLabel jlblMotivoEntrada37;
    private javax.swing.JLabel jlblMotivoEntrada38;
    private javax.swing.JLabel jlblMotivoEntrada39;
    private javax.swing.JLabel jlblMotivoEntrada4;
    private javax.swing.JLabel jlblMotivoEntrada40;
    private javax.swing.JLabel jlblMotivoEntrada41;
    private javax.swing.JLabel jlblMotivoEntrada42;
    private javax.swing.JLabel jlblMotivoEntrada43;
    private javax.swing.JLabel jlblMotivoEntrada44;
    private javax.swing.JLabel jlblMotivoEntrada45;
    private javax.swing.JLabel jlblMotivoEntrada46;
    private javax.swing.JLabel jlblMotivoEntrada47;
    private javax.swing.JLabel jlblMotivoEntrada48;
    private javax.swing.JLabel jlblMotivoEntrada49;
    private javax.swing.JLabel jlblMotivoEntrada5;
    private javax.swing.JLabel jlblMotivoEntrada50;
    private javax.swing.JLabel jlblMotivoEntrada51;
    private javax.swing.JLabel jlblMotivoEntrada52;
    private javax.swing.JLabel jlblMotivoEntrada53;
    private javax.swing.JLabel jlblMotivoEntrada54;
    private javax.swing.JLabel jlblMotivoEntrada55;
    private javax.swing.JLabel jlblMotivoEntrada56;
    private javax.swing.JLabel jlblMotivoEntrada57;
    private javax.swing.JLabel jlblMotivoEntrada58;
    private javax.swing.JLabel jlblMotivoEntrada59;
    private javax.swing.JLabel jlblMotivoEntrada6;
    private javax.swing.JLabel jlblMotivoEntrada7;
    private javax.swing.JLabel jlblMotivoEntrada8;
    private javax.swing.JLabel jlblMotivoEntrada9;
    private javax.swing.JLabel jlblTipoEntrada;
    private javax.swing.JLabel jlblTipoEntrada1;
    private javax.swing.JLabel jlblTipoEntrada10;
    private javax.swing.JLabel jlblTipoEntrada11;
    private javax.swing.JLabel jlblTipoEntrada12;
    private javax.swing.JLabel jlblTipoEntrada13;
    private javax.swing.JLabel jlblTipoEntrada14;
    private javax.swing.JLabel jlblTipoEntrada15;
    private javax.swing.JLabel jlblTipoEntrada16;
    private javax.swing.JLabel jlblTipoEntrada17;
    private javax.swing.JLabel jlblTipoEntrada18;
    private javax.swing.JLabel jlblTipoEntrada19;
    private javax.swing.JLabel jlblTipoEntrada2;
    private javax.swing.JLabel jlblTipoEntrada20;
    private javax.swing.JLabel jlblTipoEntrada21;
    private javax.swing.JLabel jlblTipoEntrada22;
    private javax.swing.JLabel jlblTipoEntrada23;
    private javax.swing.JLabel jlblTipoEntrada24;
    private javax.swing.JLabel jlblTipoEntrada25;
    private javax.swing.JLabel jlblTipoEntrada26;
    private javax.swing.JLabel jlblTipoEntrada27;
    private javax.swing.JLabel jlblTipoEntrada28;
    private javax.swing.JLabel jlblTipoEntrada29;
    private javax.swing.JLabel jlblTipoEntrada3;
    private javax.swing.JLabel jlblTipoEntrada30;
    private javax.swing.JLabel jlblTipoEntrada31;
    private javax.swing.JLabel jlblTipoEntrada32;
    private javax.swing.JLabel jlblTipoEntrada33;
    private javax.swing.JLabel jlblTipoEntrada34;
    private javax.swing.JLabel jlblTipoEntrada4;
    private javax.swing.JLabel jlblTipoEntrada5;
    private javax.swing.JLabel jlblTipoEntrada6;
    private javax.swing.JLabel jlblTipoEntrada7;
    private javax.swing.JLabel jlblTipoEntrada8;
    private javax.swing.JLabel jlblTipoEntrada9;
    private javax.swing.JRadioButton jrdbFalseEntrada;
    private javax.swing.JRadioButton jrdbFalseEntrada1;
    private javax.swing.JRadioButton jrdbFalseEntrada10;
    private javax.swing.JRadioButton jrdbFalseEntrada11;
    private javax.swing.JRadioButton jrdbFalseEntrada12;
    private javax.swing.JRadioButton jrdbFalseEntrada13;
    private javax.swing.JRadioButton jrdbFalseEntrada14;
    private javax.swing.JRadioButton jrdbFalseEntrada15;
    private javax.swing.JRadioButton jrdbFalseEntrada16;
    private javax.swing.JRadioButton jrdbFalseEntrada17;
    private javax.swing.JRadioButton jrdbFalseEntrada18;
    private javax.swing.JRadioButton jrdbFalseEntrada19;
    private javax.swing.JRadioButton jrdbFalseEntrada2;
    private javax.swing.JRadioButton jrdbFalseEntrada20;
    private javax.swing.JRadioButton jrdbFalseEntrada21;
    private javax.swing.JRadioButton jrdbFalseEntrada22;
    private javax.swing.JRadioButton jrdbFalseEntrada23;
    private javax.swing.JRadioButton jrdbFalseEntrada24;
    private javax.swing.JRadioButton jrdbFalseEntrada25;
    private javax.swing.JRadioButton jrdbFalseEntrada26;
    private javax.swing.JRadioButton jrdbFalseEntrada27;
    private javax.swing.JRadioButton jrdbFalseEntrada28;
    private javax.swing.JRadioButton jrdbFalseEntrada29;
    private javax.swing.JRadioButton jrdbFalseEntrada3;
    private javax.swing.JRadioButton jrdbFalseEntrada4;
    private javax.swing.JRadioButton jrdbFalseEntrada5;
    private javax.swing.JRadioButton jrdbFalseEntrada6;
    private javax.swing.JRadioButton jrdbFalseEntrada7;
    private javax.swing.JRadioButton jrdbFalseEntrada8;
    private javax.swing.JRadioButton jrdbFalseEntrada9;
    private javax.swing.JRadioButton jrdbTrueEntrada;
    private javax.swing.JRadioButton jrdbTrueEntrada1;
    private javax.swing.JRadioButton jrdbTrueEntrada10;
    private javax.swing.JRadioButton jrdbTrueEntrada11;
    private javax.swing.JRadioButton jrdbTrueEntrada12;
    private javax.swing.JRadioButton jrdbTrueEntrada13;
    private javax.swing.JRadioButton jrdbTrueEntrada14;
    private javax.swing.JRadioButton jrdbTrueEntrada15;
    private javax.swing.JRadioButton jrdbTrueEntrada16;
    private javax.swing.JRadioButton jrdbTrueEntrada17;
    private javax.swing.JRadioButton jrdbTrueEntrada18;
    private javax.swing.JRadioButton jrdbTrueEntrada19;
    private javax.swing.JRadioButton jrdbTrueEntrada2;
    private javax.swing.JRadioButton jrdbTrueEntrada20;
    private javax.swing.JRadioButton jrdbTrueEntrada21;
    private javax.swing.JRadioButton jrdbTrueEntrada22;
    private javax.swing.JRadioButton jrdbTrueEntrada23;
    private javax.swing.JRadioButton jrdbTrueEntrada24;
    private javax.swing.JRadioButton jrdbTrueEntrada25;
    private javax.swing.JRadioButton jrdbTrueEntrada26;
    private javax.swing.JRadioButton jrdbTrueEntrada27;
    private javax.swing.JRadioButton jrdbTrueEntrada28;
    private javax.swing.JRadioButton jrdbTrueEntrada29;
    private javax.swing.JRadioButton jrdbTrueEntrada3;
    private javax.swing.JRadioButton jrdbTrueEntrada4;
    private javax.swing.JRadioButton jrdbTrueEntrada5;
    private javax.swing.JRadioButton jrdbTrueEntrada6;
    private javax.swing.JRadioButton jrdbTrueEntrada7;
    private javax.swing.JRadioButton jrdbTrueEntrada8;
    private javax.swing.JRadioButton jrdbTrueEntrada9;
    private javax.swing.JLabel llblCerrar;
    // End of variables declaration//GEN-END:variables
}
