/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormsVigilante;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author CRISTIAN
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuV
     */
    public FrmMenuPrincipal() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        scaleImage();
        FrmLogin log = new FrmLogin();
        lblCargoSeleccioado.setText(log.cargo);
        lblNombreUsuario.setText(log.nombres + " " + log.apellidos);
        }
    
        public void scaleImage(){
        ImageIcon ImgIcon1, ImgIcon2;
        Image img1, img2;
        ImgIcon1 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Vigilante_Imagenes/imgLogoDark.png")));
        img1 = ImgIcon1.getImage();
        img2 = img1.getScaledInstance(lblImgLogo.getWidth(), lblImgLogo.getHeight(), Image.SCALE_SMOOTH);
        ImgIcon2 = new ImageIcon(img2);
        lblImgLogo.setIcon(ImgIcon2);
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPSistemaVigilantes = new javax.swing.JPanel();
        jPNombreSistema = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lblNegro = new javax.swing.JLabel();
        lblImgLogo = new javax.swing.JLabel();
        jPBotonAtras = new javax.swing.JPanel();
        btnSalida = new javax.swing.JButton();
        jPBarraSuperior = new javax.swing.JPanel();
        lblCerrrar = new javax.swing.JLabel();
        btnAmarillo = new javax.swing.JButton();
        jPNombreUsuario = new javax.swing.JPanel();
        changeThemeBtn = new javax.swing.JButton();
        lblCargoSeleccioado = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jPContenedorBotones = new javax.swing.JPanel();
        btnEntrada = new javax.swing.JButton();
        btnSalidas = new javax.swing.JButton();
        btnVisitantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPSistemaVigilantes.setBackground(new java.awt.Color(57, 62, 70));

        jPNombreSistema.setBackground(new java.awt.Color(57, 62, 70));

        lblnombre.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnombre.setText("Sistema Vigilantes");
        lblnombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblImgLogo.setFocusable(false);
        lblImgLogo.setPreferredSize(new java.awt.Dimension(232, 240));
        lblImgLogo.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPNombreSistemaLayout = new javax.swing.GroupLayout(jPNombreSistema);
        jPNombreSistema.setLayout(jPNombreSistemaLayout);
        jPNombreSistemaLayout.setHorizontalGroup(
            jPNombreSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNombreSistemaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblImgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPNombreSistemaLayout.setVerticalGroup(
            jPNombreSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNombreSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPNombreSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNombreSistemaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(lblNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPNombreSistemaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblImgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPBotonAtras.setBackground(new java.awt.Color(57, 62, 70));

        btnSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vigilante_Imagenes/imgCerrarSesionLight.png"))); // NOI18N
        btnSalida.setContentAreaFilled(false);
        btnSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBotonAtrasLayout = new javax.swing.GroupLayout(jPBotonAtras);
        jPBotonAtras.setLayout(jPBotonAtrasLayout);
        jPBotonAtrasLayout.setHorizontalGroup(
            jPBotonAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotonAtrasLayout.createSequentialGroup()
                .addComponent(btnSalida)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPBotonAtrasLayout.setVerticalGroup(
            jPBotonAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBotonAtrasLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(btnSalida)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPSistemaVigilantesLayout = new javax.swing.GroupLayout(jPSistemaVigilantes);
        jPSistemaVigilantes.setLayout(jPSistemaVigilantesLayout);
        jPSistemaVigilantesLayout.setHorizontalGroup(
            jPSistemaVigilantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSistemaVigilantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSistemaVigilantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSistemaVigilantesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPBotonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(jPSistemaVigilantesLayout.createSequentialGroup()
                        .addComponent(jPNombreSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPSistemaVigilantesLayout.setVerticalGroup(
            jPSistemaVigilantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSistemaVigilantesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPNombreSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jPBotonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        getContentPane().add(jPSistemaVigilantes);
        jPSistemaVigilantes.setBounds(0, 0, 263, 970);

        jPBarraSuperior.setBackground(new java.awt.Color(255, 211, 105));
        jPBarraSuperior.setPreferredSize(new java.awt.Dimension(1490, 60));
        jPBarraSuperior.setLayout(null);

        lblCerrrar.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        lblCerrrar.setText("x");
        lblCerrrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrrarMouseClicked(evt);
            }
        });
        jPBarraSuperior.add(lblCerrrar);
        lblCerrrar.setBounds(1330, 10, 31, 35);

        btnAmarillo.setAlignmentY(0.7F);
        btnAmarillo.setContentAreaFilled(false);
        btnAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmarilloActionPerformed(evt);
            }
        });
        jPBarraSuperior.add(btnAmarillo);
        btnAmarillo.setBounds(783, 0, 33, 54);

        jPNombreUsuario.setBackground(new java.awt.Color(255, 211, 105));

        changeThemeBtn.setAlignmentY(0.7F);
        changeThemeBtn.setContentAreaFilled(false);
        changeThemeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeThemeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeThemeBtnActionPerformed(evt);
            }
        });

        lblCargoSeleccioado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCargoSeleccioado.setText("Administrador");

        lblCargo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCargo.setText("Cargo:");

        lblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreUsuario.setText("Josué Alemán");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario.setText("Usuario:");

        javax.swing.GroupLayout jPNombreUsuarioLayout = new javax.swing.GroupLayout(jPNombreUsuario);
        jPNombreUsuario.setLayout(jPNombreUsuarioLayout);
        jPNombreUsuarioLayout.setHorizontalGroup(
            jPNombreUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNombreUsuarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblUsuario)
                .addGap(27, 27, 27)
                .addComponent(lblNombreUsuario)
                .addGap(60, 60, 60)
                .addComponent(lblCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCargoSeleccioado)
                .addGap(227, 227, 227)
                .addComponent(changeThemeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPNombreUsuarioLayout.setVerticalGroup(
            jPNombreUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNombreUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPNombreUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeThemeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPNombreUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUsuario)
                        .addComponent(lblNombreUsuario)
                        .addComponent(lblCargo)
                        .addComponent(lblCargoSeleccioado)))
                .addContainerGap())
        );

        jPBarraSuperior.add(jPNombreUsuario);
        jPNombreUsuario.setBounds(260, 0, 764, 61);

        getContentPane().add(jPBarraSuperior);
        jPBarraSuperior.setBounds(0, 0, 1490, 60);

        btnEntrada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vigilante_Imagenes/imgEntradaDark.png"))); // NOI18N
        btnEntrada.setText("Entrada");
        btnEntrada.setContentAreaFilled(false);
        btnEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnSalidas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vigilante_Imagenes/imgEntradaDark.png"))); // NOI18N
        btnSalidas.setText("Salida");
        btnSalidas.setContentAreaFilled(false);
        btnSalidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalidas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalidas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidasActionPerformed(evt);
            }
        });

        btnVisitantes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVisitantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vigilante_Imagenes/imgVisitanteDark.png"))); // NOI18N
        btnVisitantes.setText("Visitantes");
        btnVisitantes.setContentAreaFilled(false);
        btnVisitantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisitantes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVisitantes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPContenedorBotonesLayout = new javax.swing.GroupLayout(jPContenedorBotones);
        jPContenedorBotones.setLayout(jPContenedorBotonesLayout);
        jPContenedorBotonesLayout.setHorizontalGroup(
            jPContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContenedorBotonesLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPContenedorBotonesLayout.setVerticalGroup(
            jPContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContenedorBotonesLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addGroup(jPContenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );

        getContentPane().add(jPContenedorBotones);
        jPContenedorBotones.setBounds(280, 70, 1110, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrrarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblCerrrarMouseClicked

    private void changeThemeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeThemeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeThemeBtnActionPerformed

    private void btnVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitantesActionPerformed
        FrmMenuVisitante MV = new FrmMenuVisitante();
        MV.show();
        dispose();
    }//GEN-LAST:event_btnVisitantesActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        FrmMenuEntrada ME = new FrmMenuEntrada();
        ME.show();
        dispose();
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidasActionPerformed
        FrmMenuSalida MS = new FrmMenuSalida();
        MS.show();
        dispose();
    }//GEN-LAST:event_btnSalidasActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        FrmLogin login = new FrmLogin();
        login.show();
        dispose();
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmarilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAmarilloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmarillo;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnSalidas;
    private javax.swing.JButton btnVisitantes;
    private javax.swing.JButton changeThemeBtn;
    private javax.swing.JPanel jPBarraSuperior;
    private javax.swing.JPanel jPBotonAtras;
    private javax.swing.JPanel jPContenedorBotones;
    private javax.swing.JPanel jPNombreSistema;
    private javax.swing.JPanel jPNombreUsuario;
    private javax.swing.JPanel jPSistemaVigilantes;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCargoSeleccioado;
    private javax.swing.JLabel lblCerrrar;
    private javax.swing.JLabel lblImgLogo;
    private javax.swing.JLabel lblNegro;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblnombre;
    // End of variables declaration//GEN-END:variables
}
