/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormsVigilante;

import Clases.Conexion;
import java.sql.Connection;
import ControladorVigilante.SalidaController;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author josue
 */
public class FrmSalidaVisitante extends javax.swing.JFrame {
    private Conexion enlace = new Conexion();
    private Connection conect = enlace.conectar();
    private SalidaController SC = new SalidaController();
    /**
     * Creates new form SalidaVisitante
     */
    public FrmSalidaVisitante() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        //Cargando los difentes combobox a utilizar        
        this.cmbPortonSalida.setModel(SC.consultarPorton());
        this.cmbVisitante.setModel(SC.consultarVisitante());
        this.cmbTipoES.setModel(SC.consultarTipoES());
        //Cargar tablas        
        CargarDatosTabla();        
        //Llenar hora y fehca de Ingreso         
        jFTfechaHora.setText(fechaActual());
        //Llenar datos del usuario
        FrmLogin log = new FrmLogin();
        lblCargoUsuario.setText(log.cargo);
        lblNombreUsuario.setText(log.nombres + " " + log.apellidos);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFTidZona = new javax.swing.JTextField();
        jPContainer = new javax.swing.JPanel();
        jPSalidaVisitante = new javax.swing.JPanel();
        lblVisitante = new javax.swing.JLabel();
        lblTipoPorton = new javax.swing.JLabel();
        cmbVisitante = new javax.swing.JComboBox<>();
        jSTablaDatos = new javax.swing.JScrollPane();
        jTRegistroSalida = new javax.swing.JTable();
        jPBotones = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblPortonSalida = new javax.swing.JLabel();
        cmbPortonSalida = new javax.swing.JComboBox<>();
        lblSalidaVisitante = new javax.swing.JLabel();
        cmbTipoES = new javax.swing.JComboBox<>();
        lblIdRegistroSalida = new javax.swing.JLabel();
        jFTidSalida = new javax.swing.JTextField();
        lblHoraFecha = new javax.swing.JLabel();
        jFTfechaHora = new javax.swing.JTextField();
        jPToolStrip = new javax.swing.JPanel();
        lblExitButton = new javax.swing.JLabel();
        lblCargoUsuario = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jPSideBar = new javax.swing.JPanel();
        jPImageContainer = new javax.swing.JPanel();
        lblSistemaVigilantes = new javax.swing.JLabel();
        lblImgBusqueda = new javax.swing.JLabel();
        jPbtnSBContainer = new javax.swing.JPanel();
        btnGoLogIn = new javax.swing.JButton();

        jFTidZona.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jFTidZona.setPreferredSize(new java.awt.Dimension(6, 30));
        jFTidZona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTidZonaKeyTyped(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPContainer.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPContainer.setLayout(null);

        jPSalidaVisitante.setBackground(new java.awt.Color(255, 255, 255));
        jPSalidaVisitante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblVisitante.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblVisitante.setText("Visitante:");

        lblTipoPorton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTipoPorton.setText("Tipo de Porton:");

        cmbVisitante.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbIdResidenciaActionPerformed(evt);
            }
        });

        jTRegistroSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Estado del Ingreso", "Tipo de entrada", "Zona"
            }
        ));
        jSTablaDatos.setViewportView(jTRegistroSalida);

        jPBotones.setBackground(new java.awt.Color(255, 255, 255));

        btnModificar.setBackground(new java.awt.Color(255, 211, 105));
        btnModificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 105), 3, true));
        btnModificar.setContentAreaFilled(false);
        btnModificar.setFocusable(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 211, 105));
        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 105), 3, true));
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setFocusable(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(255, 211, 105));
        btnRegistrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 105), 3, true));
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setFocusable(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(255, 211, 105));
        btnConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 105), 3, true));
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setFocusable(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBotonesLayout = new javax.swing.GroupLayout(jPBotones);
        jPBotones.setLayout(jPBotonesLayout);
        jPBotonesLayout.setHorizontalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBotonesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPBotonesLayout.setVerticalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBotonesLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        lblPortonSalida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPortonSalida.setText("Porton de Salida:");

        cmbPortonSalida.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbPortonSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbPortonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPortonSalidaActionPerformed(evt);
            }
        });

        lblSalidaVisitante.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSalidaVisitante.setForeground(new java.awt.Color(255, 211, 105));
        lblSalidaVisitante.setText("Salida de Visitantes");

        cmbTipoES.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbTipoES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoESjcmbIdResidenciaActionPerformed(evt);
            }
        });

        lblIdRegistroSalida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblIdRegistroSalida.setText("N° Registro de Salida:");

        jFTidSalida.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jFTidSalida.setPreferredSize(new java.awt.Dimension(6, 30));
        jFTidSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTidSalidaKeyTyped(evt);
            }
        });

        lblHoraFecha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHoraFecha.setText("Hora de Salida:");

        jFTfechaHora.setEditable(false);
        jFTfechaHora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jFTfechaHora.setPreferredSize(new java.awt.Dimension(6, 30));
        jFTfechaHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTfechaHoraKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPSalidaVisitanteLayout = new javax.swing.GroupLayout(jPSalidaVisitante);
        jPSalidaVisitante.setLayout(jPSalidaVisitanteLayout);
        jPSalidaVisitanteLayout.setHorizontalGroup(
            jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSalidaVisitanteLayout.createSequentialGroup()
                .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPSalidaVisitanteLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPSalidaVisitanteLayout.createSequentialGroup()
                                .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPortonSalida)
                                    .addComponent(cmbPortonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVisitante)
                                    .addComponent(cmbVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoPorton)
                                    .addComponent(cmbTipoES, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(jPSalidaVisitanteLayout.createSequentialGroup()
                                .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSTablaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPSalidaVisitanteLayout.createSequentialGroup()
                                        .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFTidSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblIdRegistroSalida))
                                        .addGap(45, 45, 45)
                                        .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFTfechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblHoraFecha))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPSalidaVisitanteLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPSalidaVisitanteLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(lblSalidaVisitante)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPSalidaVisitanteLayout.setVerticalGroup(
            jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSalidaVisitanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalidaVisitante)
                .addGap(27, 27, 27)
                .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPortonSalida)
                    .addComponent(lblVisitante)
                    .addComponent(lblTipoPorton))
                .addGap(18, 18, 18)
                .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPortonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPSalidaVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPSalidaVisitanteLayout.createSequentialGroup()
                        .addComponent(lblIdRegistroSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFTidSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPSalidaVisitanteLayout.createSequentialGroup()
                        .addComponent(lblHoraFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFTfechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jSTablaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPContainer.add(jPSalidaVisitante);
        jPSalidaVisitante.setBounds(10, 10, 1050, 680);

        getContentPane().add(jPContainer);
        jPContainer.setBounds(290, 60, 1098, 710);

        jPToolStrip.setBackground(new java.awt.Color(255, 211, 105));
        jPToolStrip.setMinimumSize(new java.awt.Dimension(1082, 61));

        lblExitButton.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        lblExitButton.setText("x");
        lblExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitButtonMouseClicked(evt);
            }
        });

        lblCargoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCargoUsuario.setText("Administrador");

        lblCargo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCargo.setText("Cargo:");

        lblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreUsuario.setText("Josué Alemán");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario.setText("Usuario:");

        javax.swing.GroupLayout jPToolStripLayout = new javax.swing.GroupLayout(jPToolStrip);
        jPToolStrip.setLayout(jPToolStripLayout);
        jPToolStripLayout.setHorizontalGroup(
            jPToolStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPToolStripLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblUsuario)
                .addGap(27, 27, 27)
                .addComponent(lblNombreUsuario)
                .addGap(60, 60, 60)
                .addComponent(lblCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCargoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 560, Short.MAX_VALUE)
                .addComponent(lblExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPToolStripLayout.setVerticalGroup(
            jPToolStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPToolStripLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPToolStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPToolStripLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPToolStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario)
                            .addComponent(lblNombreUsuario)
                            .addComponent(lblCargo)
                            .addComponent(lblCargoUsuario))))
                .addContainerGap())
        );

        getContentPane().add(jPToolStrip);
        jPToolStrip.setBounds(290, 0, 1080, 61);

        jPSideBar.setBackground(new java.awt.Color(57, 62, 70));
        jPSideBar.setPreferredSize(new java.awt.Dimension(287, 811));
        jPSideBar.setRequestFocusEnabled(false);

        jPImageContainer.setBackground(new java.awt.Color(57, 62, 70));

        lblSistemaVigilantes.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblSistemaVigilantes.setForeground(new java.awt.Color(255, 255, 255));
        lblSistemaVigilantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSistemaVigilantes.setText("Sistema Vigilantes");
        lblSistemaVigilantes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblImgBusqueda.setFocusable(false);
        lblImgBusqueda.setPreferredSize(new java.awt.Dimension(232, 240));
        lblImgBusqueda.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPImageContainerLayout = new javax.swing.GroupLayout(jPImageContainer);
        jPImageContainer.setLayout(jPImageContainerLayout);
        jPImageContainerLayout.setHorizontalGroup(
            jPImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSistemaVigilantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPImageContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPImageContainerLayout.setVerticalGroup(
            jPImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPImageContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSistemaVigilantes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lblImgBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPbtnSBContainer.setBackground(new java.awt.Color(57, 62, 70));

        btnGoLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vigilante_Imagenes/imgCerrarSesionLight.png"))); // NOI18N
        btnGoLogIn.setContentAreaFilled(false);
        btnGoLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoLogInMouseClicked(evt);
            }
        });
        btnGoLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPbtnSBContainerLayout = new javax.swing.GroupLayout(jPbtnSBContainer);
        jPbtnSBContainer.setLayout(jPbtnSBContainerLayout);
        jPbtnSBContainerLayout.setHorizontalGroup(
            jPbtnSBContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbtnSBContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGoLogIn)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPbtnSBContainerLayout.setVerticalGroup(
            jPbtnSBContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbtnSBContainerLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(btnGoLogIn)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout jPSideBarLayout = new javax.swing.GroupLayout(jPSideBar);
        jPSideBar.setLayout(jPSideBarLayout);
        jPSideBarLayout.setHorizontalGroup(
            jPSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPImageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSideBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPbtnSBContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPSideBarLayout.setVerticalGroup(
            jPSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSideBarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPImageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jPbtnSBContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPSideBar);
        jPSideBar.setBounds(0, 0, 287, 811);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPortonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPortonSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPortonSalidaActionPerformed

    private void jcmbIdResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbIdResidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbIdResidenciaActionPerformed

    private void cmbTipoESjcmbIdResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoESjcmbIdResidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoESjcmbIdResidenciaActionPerformed

    private void lblExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitButtonMouseClicked
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.show();
        dispose();
    }//GEN-LAST:event_lblExitButtonMouseClicked

    private void btnGoLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoLogInMouseClicked
        FrmLogin login = new FrmLogin();
        login.show();
        dispose();
    }//GEN-LAST:event_btnGoLogInMouseClicked

    private void btnGoLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoLogInActionPerformed
        FrmLogin login = new FrmLogin();
        login.show();
        dispose();
    }//GEN-LAST:event_btnGoLogInActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Limpiar y resetear los campos
        LimpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //Verificar que no se manden datos vacios o invalidos.
        if (cmbPortonSalida.getSelectedIndex() == 0 || cmbVisitante.getSelectedIndex() == 0 || cmbTipoES.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,"Campos vacios, verificar que los campos esten llenos");  
        } 
        else{
            // Registrar los datos a la Tabla registro Salida
            SC.setIdPorton(Integer.parseInt(cmbPortonSalida.getSelectedItem().toString()));
            SC.convertirVisitante(cmbVisitante.getSelectedItem().toString());
            SC.convertirTipoES(cmbTipoES.getSelectedItem().toString());
            SC.setFechaHora(jFTfechaHora.getText());
            //Enviando los datos a SQL
            if (SC.guardarSalida()) {
                JOptionPane.showMessageDialog(this,"Datos guardados exitosamente");
                CargarDatosTabla();
            }
            else{
                JOptionPane.showMessageDialog(this,"Datos no guardados");
            }
            LimpiarCampos();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Verificar que no se manden datos vacios o invalidos.
        if (cmbPortonSalida.getSelectedIndex() == 0 || cmbVisitante.getSelectedIndex() == 0 || cmbTipoES.getSelectedIndex() == 0 || jFTidSalida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Campos vacios, verificar que los campos esten llenos");  
        } 
        else{
            // Actualizar los datos a la Tabla registro Salida
            SC.setIdRegistroSalida(Integer.parseInt(jFTidSalida.getText()));
            SC.setIdPorton(Integer.parseInt(cmbPortonSalida.getSelectedItem().toString()));
            SC.convertirVisitante(cmbVisitante.getSelectedItem().toString());
            SC.convertirTipoES(cmbTipoES.getSelectedItem().toString()); 
            SC.setFechaHora(jFTfechaHora.getText());
            //Enviando los datos a SQL
            if (SC.modificarSalida()) {
                JOptionPane.showMessageDialog(this,"Datos actualizados exitosamente");
                CargarDatosTabla();
            }
            else{
                JOptionPane.showMessageDialog(this,"Datos no actualizados");
            }
            LimpiarCampos();
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void jFTidZonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTidZonaKeyTyped
        //Solo permitir paso de números
        if(SoloNumero(evt.getKeyChar())){
            //no deja que se escriba un letras
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar números");
        }
    }//GEN-LAST:event_jFTidZonaKeyTyped

    private void jFTidSalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTidSalidaKeyTyped
        //Solo permitir paso de números
        if(SoloNumero(evt.getKeyChar())){
            //no deja que se escriba un letras
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar números");
        }
    }//GEN-LAST:event_jFTidSalidaKeyTyped

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (jFTidSalida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Campos vacios, verificar que los campos esten llenos");   
        }
        else{
            //Consular
            //Realizar Consulta
            SC.setIdRegistroSalida(Integer.parseInt(jFTidSalida.getText()));
            if (SC.consultarSalida()) {
                jFTidZona.setText(String.valueOf(SC.getIdRegistroSalida()));
                cmbPortonSalida.setSelectedIndex(SC.getIdPorton());
                cmbVisitante.setSelectedIndex(SC.getIdVisitante());
                cmbTipoES.setSelectedIndex(SC.getIdTipoES());
                jFTfechaHora.setText(SC.getFechaHora());
                this.jTRegistroSalida.setModel(SC.filtrarDatosTabla());
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al consultar");
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jFTfechaHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTfechaHoraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTfechaHoraKeyTyped
    

    //Metodos
    //Para validar que solo permitan pasar Numeros
    public boolean SoloNumero(char numero){
        if(Character.isDigit(numero) || Character.isISOControl(numero)){
            return false;
        }
        else{
            return true;
        }
    }
    
    //Limpiar Campos
    public void LimpiarCampos(){
        jFTidSalida.setText("");
        cmbPortonSalida.setSelectedIndex(1);
        cmbVisitante.setSelectedIndex(1);
        cmbTipoES.setSelectedIndex(1);
    }
    
    //Cargar Tablas
    public void CargarDatosTabla(){
        this.jTRegistroSalida.setModel(SC.consultarDatosTabla());
    }
    
    //Obtener la hora actual
    private String fechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formatoFecha= new SimpleDateFormat("YYYY-MM-dd hh:mm:ss");
        return formatoFecha.format(fecha);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSalidaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSalidaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSalidaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSalidaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSalidaVisitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGoLogIn;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbPortonSalida;
    private javax.swing.JComboBox<String> cmbTipoES;
    private javax.swing.JComboBox<String> cmbVisitante;
    private javax.swing.JTextField jFTfechaHora;
    private javax.swing.JTextField jFTidSalida;
    private javax.swing.JTextField jFTidZona;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JPanel jPContainer;
    private javax.swing.JPanel jPImageContainer;
    private javax.swing.JPanel jPSalidaVisitante;
    private javax.swing.JPanel jPSideBar;
    private javax.swing.JPanel jPToolStrip;
    private javax.swing.JPanel jPbtnSBContainer;
    private javax.swing.JScrollPane jSTablaDatos;
    private javax.swing.JTable jTRegistroSalida;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCargoUsuario;
    private javax.swing.JLabel lblExitButton;
    private javax.swing.JLabel lblHoraFecha;
    private javax.swing.JLabel lblIdRegistroSalida;
    private javax.swing.JLabel lblImgBusqueda;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPortonSalida;
    private javax.swing.JLabel lblSalidaVisitante;
    private javax.swing.JLabel lblSistemaVigilantes;
    private javax.swing.JLabel lblTipoPorton;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVisitante;
    // End of variables declaration//GEN-END:variables
}
