/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormsVigilante;

import Clases.Conexion;
import ControladorVigilante.PersonalController;
import FormsVigilante.FrmLogin;
import FormsVigilante.FrmVisualizarPersonal;
import com.toedter.calendar.JTextFieldDateEditor;
import java.net.URLDecoder;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author CRISTIAN
 */
public class FrmVisualizarReporteVigilantes extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarEntrada
     */
    public FrmVisualizarReporteVigilantes() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        inicializar();
    }
    private void inicializar(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPToolStrip = new javax.swing.JPanel();
        lblExitButton4 = new javax.swing.JLabel();
        LblBusquedaVisitante1 = new javax.swing.JLabel();
        LblBusquedaVisitante = new javax.swing.JLabel();
        LblBusquedaVisitante2 = new javax.swing.JLabel();
        jCostoInicial = new javax.swing.JTextField();
        jCostoFinal = new javax.swing.JTextField();
        jPBusquedaContainer = new javax.swing.JPanel();
        jbtnImprimir = new javax.swing.JButton();
        LblBusquedaVisitante3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1074, 289));
        getContentPane().setLayout(null);

        jPContainer.setBackground(new java.awt.Color(57, 62, 70));
        jPContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIGILANTE");

        javax.swing.GroupLayout jPContainerLayout = new javax.swing.GroupLayout(jPContainer);
        jPContainer.setLayout(jPContainerLayout);
        jPContainerLayout.setHorizontalGroup(
            jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContainerLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPContainerLayout.setVerticalGroup(
            jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContainerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(737, Short.MAX_VALUE))
        );

        getContentPane().add(jPContainer);
        jPContainer.setBounds(0, 0, 209, 804);

        jPToolStrip.setBackground(new java.awt.Color(255, 211, 105));

        lblExitButton4.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        lblExitButton4.setText("x");
        lblExitButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExitButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitButtonMouseClicked(evt);
            }
        });

        LblBusquedaVisitante1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LblBusquedaVisitante1.setText("GENERAR REPORTE");

        javax.swing.GroupLayout jPToolStripLayout = new javax.swing.GroupLayout(jPToolStrip);
        jPToolStrip.setLayout(jPToolStripLayout);
        jPToolStripLayout.setHorizontalGroup(
            jPToolStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPToolStripLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(LblBusquedaVisitante1)
                .addGap(577, 577, 577)
                .addComponent(lblExitButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPToolStripLayout.setVerticalGroup(
            jPToolStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPToolStripLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPToolStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblExitButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPToolStripLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(LblBusquedaVisitante1)))
                .addContainerGap())
        );

        getContentPane().add(jPToolStrip);
        jPToolStrip.setBounds(190, 0, 1082, 61);

        LblBusquedaVisitante.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblBusquedaVisitante.setText("($) Costo Inicial:");
        getContentPane().add(LblBusquedaVisitante);
        LblBusquedaVisitante.setBounds(280, 180, 190, 22);

        LblBusquedaVisitante2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblBusquedaVisitante2.setText("($) Costo Final:");
        getContentPane().add(LblBusquedaVisitante2);
        LblBusquedaVisitante2.setBounds(530, 180, 170, 22);

        jCostoInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCostoInicialKeyTyped(evt);
            }
        });
        getContentPane().add(jCostoInicial);
        jCostoInicial.setBounds(280, 220, 170, 30);

        jCostoFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCostoFinalKeyTyped(evt);
            }
        });
        getContentPane().add(jCostoFinal);
        jCostoFinal.setBounds(540, 220, 170, 30);

        jPBusquedaContainer.setLayout(null);

        jbtnImprimir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnImprimir.setText("Imprimir Reporte");
        jbtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImprimirActionPerformed(evt);
            }
        });
        jPBusquedaContainer.add(jbtnImprimir);
        jbtnImprimir.setBounds(570, 30, 198, 39);

        getContentPane().add(jPBusquedaContainer);
        jPBusquedaContainer.setBounds(250, 170, 840, 100);

        LblBusquedaVisitante3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LblBusquedaVisitante3.setText("GENERAR REPORTE: Vigilante");
        getContentPane().add(LblBusquedaVisitante3);
        LblBusquedaVisitante3.setBounds(280, 100, 390, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void LlamarReportes(String nombre, Map parametros){
        Conexion enlace = new Conexion();
        Connection conect = enlace.conectar();
        try{
            JasperReport report = JasperCompileManager.compileReport("src/reportes/"+nombre+".jrxml");
            JasperPrint print = JasperFillManager.fillReport(report,parametros,conect);
            JasperViewer view = new JasperViewer(print,false); 
            view.setVisible(true);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error al generar reporte:" + ex.getMessage() );
        }
        
    }    
    
    private void jbtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimirActionPerformed
        
        if (jCostoInicial.getText().trim().length() == 0 || jCostoFinal.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Error: Hay campos vacíos");
            return;
        }
        
        Integer CostoInicial = Integer.parseInt(jCostoInicial.getText());
        Integer CostoFinal = Integer.parseInt(jCostoFinal.getText());
        
        if (CostoFinal < CostoInicial) {
            JOptionPane.showMessageDialog(this, "El rango de costos debe ser consecutivo");
        }
        else{
            Map Parametros = new HashMap();
            Parametros.put("CostoInicial", CostoInicial);
            Parametros.put("CostoFinal", CostoFinal);
            FrmLogin log = new FrmLogin();
            Parametros.put("Administrador", log.nombres + " " + log.apellidos);
            LlamarReportes("ReporteVigilante",Parametros);
        }
        
    }//GEN-LAST:event_jbtnImprimirActionPerformed

    private void lblExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitButtonMouseClicked
        FrmVisualizarPersonal vp = new FrmVisualizarPersonal();
        vp.show();
        dispose();
    }//GEN-LAST:event_lblExitButtonMouseClicked

    private void jCostoInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCostoInicialKeyTyped
        //Solo permitir paso de numeros
        if(SoloNumero(evt.getKeyChar())){
           //no deja que se escriba un letra
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar números");
        }
    }//GEN-LAST:event_jCostoInicialKeyTyped

    private void jCostoFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCostoFinalKeyTyped
        //Solo permitir paso de numeros
        if(SoloNumero(evt.getKeyChar())){
           //no deja que se escriba un letra
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar números");
        }
    }//GEN-LAST:event_jCostoFinalKeyTyped

    //Metodos
    //Para validar que solo permitan pasar Numeros
    public boolean SoloNumero(char numero){
        if(Character.isDigit(numero) || Character.isISOControl(numero)){
            return false;
        }
        else{
            return true;
        }
    }

    //Limpiar campos
    public void LimpiarCampos(){

    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarReporteVigilantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarReporteVigilantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarReporteVigilantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarReporteVigilantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVisualizarReporteVigilantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblBusquedaVisitante;
    private javax.swing.JLabel LblBusquedaVisitante1;
    private javax.swing.JLabel LblBusquedaVisitante2;
    private javax.swing.JLabel LblBusquedaVisitante3;
    private javax.swing.JTextField jCostoFinal;
    private javax.swing.JTextField jCostoInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPBusquedaContainer;
    private javax.swing.JPanel jPContainer;
    private javax.swing.JPanel jPToolStrip;
    private javax.swing.JButton jbtnImprimir;
    private javax.swing.JLabel lblExitButton4;
    // End of variables declaration//GEN-END:variables
}
