/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormsReportes;

import Clases.Conexion;
import ControladorVigilante.HorarioController;
import FormsVigilante.FrmLogin;
import FormsVigilante.FrmVisualizarHorario;
import com.toedter.calendar.JTextFieldDateEditor;
import java.net.URLDecoder;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author CRISTIAN
 */
public class FrmVisualizarReporteHorarios extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarEntrada
     */
    public FrmVisualizarReporteHorarios() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        inicializar();
    }
    private void inicializar(){
        //deshabilitar
        try {
            JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateFechaInicio.getDateEditor();
            editor.setEditable(false); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo deshabilitar");
        }
        
        try {
            JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateFechaFin.getDateEditor();
            editor.setEditable(false); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo deshabilitar");
        }
        
        Calendar today = Calendar.getInstance();
        today.set(Calendar.HOUR_OF_DAY, 0);
        
        jDateFechaInicio.setDate(today.getTime());
        jDateFechaFin.setDate(today.getTime());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBusquedaContainer = new javax.swing.JPanel();
        LblBusquedaVisitante = new javax.swing.JLabel();
        jbtnImprimir = new javax.swing.JButton();
        LblBusquedaVisitante2 = new javax.swing.JLabel();
        jDateFechaInicio = new com.toedter.calendar.JDateChooser();
        jDateFechaFin = new com.toedter.calendar.JDateChooser();
        jPContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPToolStrip = new javax.swing.JPanel();
        lblExitButton = new javax.swing.JLabel();
        LblBusquedaVisitante1 = new javax.swing.JLabel();
        LblBusquedaVisitante3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1074, 289));
        getContentPane().setLayout(null);

        jPBusquedaContainer.setLayout(null);

        LblBusquedaVisitante.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblBusquedaVisitante.setText("Fecha Inicio:");
        jPBusquedaContainer.add(LblBusquedaVisitante);
        LblBusquedaVisitante.setBounds(40, 10, 112, 22);

        jbtnImprimir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnImprimir.setText("Imprimir Reporte");
        jbtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImprimirActionPerformed(evt);
            }
        });
        jPBusquedaContainer.add(jbtnImprimir);
        jbtnImprimir.setBounds(610, 30, 198, 39);

        LblBusquedaVisitante2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblBusquedaVisitante2.setText("Fecha Fin:");
        jPBusquedaContainer.add(LblBusquedaVisitante2);
        LblBusquedaVisitante2.setBounds(290, 10, 130, 22);
        jPBusquedaContainer.add(jDateFechaInicio);
        jDateFechaInicio.setBounds(40, 50, 210, 30);
        jPBusquedaContainer.add(jDateFechaFin);
        jDateFechaFin.setBounds(290, 50, 220, 30);

        getContentPane().add(jPBusquedaContainer);
        jPBusquedaContainer.setBounds(230, 160, 840, 100);

        jPContainer.setBackground(new java.awt.Color(57, 62, 70));
        jPContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIGILANTE");

        javax.swing.GroupLayout jPContainerLayout = new javax.swing.GroupLayout(jPContainer);
        jPContainer.setLayout(jPContainerLayout);
        jPContainerLayout.setHorizontalGroup(
            jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContainerLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPContainerLayout.setVerticalGroup(
            jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContainerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(737, Short.MAX_VALUE))
        );

        getContentPane().add(jPContainer);
        jPContainer.setBounds(0, 0, 209, 804);

        jPToolStrip.setBackground(new java.awt.Color(255, 211, 105));

        lblExitButton.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        lblExitButton.setText("x");
        lblExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitButtonMouseClicked(evt);
            }
        });

        LblBusquedaVisitante1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LblBusquedaVisitante1.setText("GENERAR REPORTE");

        javax.swing.GroupLayout jPToolStripLayout = new javax.swing.GroupLayout(jPToolStrip);
        jPToolStrip.setLayout(jPToolStripLayout);
        jPToolStripLayout.setHorizontalGroup(
            jPToolStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPToolStripLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(LblBusquedaVisitante1)
                .addGap(577, 577, 577)
                .addComponent(lblExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPToolStripLayout.setVerticalGroup(
            jPToolStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPToolStripLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPToolStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPToolStripLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(LblBusquedaVisitante1)))
                .addContainerGap())
        );

        getContentPane().add(jPToolStrip);
        jPToolStrip.setBounds(190, 0, 1082, 61);

        LblBusquedaVisitante3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LblBusquedaVisitante3.setText("GENERAR REPORTE: Horario");
        getContentPane().add(LblBusquedaVisitante3);
        LblBusquedaVisitante3.setBounds(270, 100, 390, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitButtonMouseClicked
        FrmVisualizarHorario vh = new FrmVisualizarHorario();
        vh.show();
        dispose();
    }//GEN-LAST:event_lblExitButtonMouseClicked

    public void LlamarReportes(String nombre, Map parametros){
        Conexion enlace = new Conexion();
        Connection conect = enlace.conectar();
        try{
            JasperReport report = JasperCompileManager.compileReport("src/reportes/"+nombre+".jrxml");
            JasperPrint print = JasperFillManager.fillReport(report,parametros,conect);
            JasperViewer view = new JasperViewer(print,false); 
            view.setVisible(true);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error al generar reporte:" + ex.getMessage() );
        }
        
    }    
    
    
    private void jbtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimirActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateInicio = dateFormat.format(jDateFechaInicio.getDate());
        String dateFin = dateFormat.format(jDateFechaFin.getDate());
                       
        
         if(dateFin.compareTo(dateInicio) < 0){
            JOptionPane.showMessageDialog(this, "Error: Fecha Fin antes de Fecha Inicio");
            return;
        }
        else{
            Map Parametros = new HashMap();
            Parametros.put("FechaInicio", dateInicio);
            Parametros.put("FechaFin", dateFin);
            FrmLogin log = new FrmLogin();
            Parametros.put("Administrador", log.nombres + " " + log.apellidos);
            LlamarReportes("ReporteHorario",Parametros);
        }
        
    }//GEN-LAST:event_jbtnImprimirActionPerformed

    //Metodos
    //Para validar que solo permitan pasar Numeros
    public boolean SoloNumero(char numero){
        if(Character.isDigit(numero) || Character.isISOControl(numero)){
            return false;
        }
        else{
            return true;
        }
    }

    //Limpiar campos
    public void LimpiarCampos(){

    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarReporteHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarReporteHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarReporteHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarReporteHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVisualizarReporteHorarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblBusquedaVisitante;
    private javax.swing.JLabel LblBusquedaVisitante1;
    private javax.swing.JLabel LblBusquedaVisitante2;
    private javax.swing.JLabel LblBusquedaVisitante3;
    private com.toedter.calendar.JDateChooser jDateFechaFin;
    private com.toedter.calendar.JDateChooser jDateFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPBusquedaContainer;
    private javax.swing.JPanel jPContainer;
    private javax.swing.JPanel jPToolStrip;
    private javax.swing.JButton jbtnImprimir;
    private javax.swing.JLabel lblExitButton;
    // End of variables declaration//GEN-END:variables
}
